collections:
  # 核心 collections - 指定兼容版本
  - name: ansible.netcommon
    version: ">=8.2.0"  # 支持 2.15.x 的最新版本
  
  - name: ansible.utils
    version: ">=2.11.0"  # 支持 2.15.x
  
  - name: community.network
    version: ">=6.0.0"   # 支持 2.15.x
  
  # 厂商 collections
  - name: cisco.ios
    version: ">=4.8.0"
  
  - name: junipernetworks.junos
    version: ">=5.0.0"
  
  - name: arista.eos
    version: ">=6.0.0"

# 如果需要 roles 也可以添加
# roles:
#   - name: username.role_name
#     version: v1.0.0
