# requirements.yml
collections:
  # 基础网络 collection
  - name: ansible.netcommon
    version: ">=8.2.0"
  
  # 厂商特定 collections
  - name: cisco.ios
    version: ">=4.8.0"
  
  - name: junipernetworks.junos
    version: ">=4.0.0"
  
  - name: arista.eos
    version: ">=6.0.0"
  
  # 华为交换机 collection - 关键！
  - name: huawei.enterprise
    version: ">=1.0.0"
  
  # 华为 CloudEngine (CE) 交换机
  - name: huawei.cloudengine
    version: ">=1.0.0"
  
  # 华为 NE 系列路由器
  - name: huawei.ne
    version: ">=1.0.0"

# 如果需要 roles 也可以添加
# roles:
#   - name: huawei.enterprise
#     version: v1.0.0
