# test_connection.yml
---
- name: 测试华为交换机连接
  hosts: 172.20.149.201
  gather_facts: false
  
  tasks:
    # 尝试不同的 network_os 值
    - name: 尝试 network_os huawei
      ansible.netcommon.cli_command:
        command: display version
      register: result_huawei
      vars:
        ansible_connection: network_cli
        ansible_network_os: huawei
      ignore_errors: yes
    
    - name: 尝试 network_os ce
      ansible.netcommon.cli_command:
        command: display version
      register: result_ce
      vars:
        ansible_connection: network_cli
        ansible_network_os: ce
      ignore_errors: yes
    
    - name: 尝试 network_os vrp
      ansible.netcommon.cli_command:
        command: display version
      register: result_vrp
      vars:
        ansible_connection: network_cli
        ansible_network_os: vrp
      ignore_errors: yes
    
    - name: 显示结果
      debug:
        msg: |
          华为连接测试结果：
          network_os=huawei: {{ "成功" if result_huawei.failed == false else "失败" }}
          network_os=ce: {{ "成功" if result_ce.failed == false else "失败" }}
          network_os=vrp: {{ "成功" if result_vrp.failed == false else "失败" }}
